FROM boredland/omeka-s-docker

ADD https://github.com/Daniel-KM/Omeka-S-module-IiifServer/releases/download/3.5.10/IiifServer.zip /var/www/html/modules/
RUN cd /var/www/html/modules && unzip IiifServer.zip
#RUN cd /var/www/html/modules/IiifServer && composer install

# enable the CORS header module of apache
RUN a2enmod headers

COPY ./htaccessmods htaccessmods
RUN cat htaccessmods >> /var/www/html/.htaccess

