FROM boredland/omeka-s-docker

RUN cd /var/www/html/modules && rm -rf *

ADD https://github.com/Daniel-KM/Omeka-S-module-IiifServer/releases/download/3.5.10/IiifServer.zip /var/www/html/modules/
RUN cd /var/www/html/modules && unzip IiifServer.zip
#RUN cd /var/www/html/modules/IiifServer && composer install

# enable the CORS header module of apache
RUN a2enmod headers

COPY ./htaccessmods htaccessmods
RUN cat htaccessmods >> /var/www/html/.htaccess

ADD https://github.com/Daniel-KM/Omeka-S-module-UniversalViewer/releases/download/3.5.8/UniversalViewer.zip /var/www/html/modules
RUN cd /var/www/html/modules/ && unzip UniversalViewer.zip

RUN cd /var/www/html/modules && curl "https://api.github.com/users/omeka-s-modules/repos?page=$PAGE&per_page=100" | grep -e 'git_url*' | cut -d \" -f 4 | xargs -L1 git clone

RUN cd /var/www/html/themes && rm -rf *
RUN cd /var/www/html/themes && curl "https://api.github.com/users/omeka-s-themes/repos?page=$PAGE&per_page=100" | grep -e 'git_url*' | cut -d \" -f 4 | xargs -L1 git clone

